### ISSUE TITLE
Linking Everything

### ISSUE THREAD

**Issue by basilfx** [DennesTorres/HttpBinding#1]
According to your [blog](https://www.red-gate.com/simple-talk/blogs/custom-binding-azure-functions/), you should use the following to link it together:

```csharp
// IWebJobsBuilders instance
var wbBuilder = builder.Services.AddWebJobs(x => { return; });

// And now you can use AddExtension
wbBuilder.AddExtension<BindingExtensionProvider>();
```

I have my doubts about `builder.Services.AddWebJobs(x => { return; });`. Looking at the [implementation](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Hosting/WebJobsServiceCollectionExtensions.cs#L41) of `AddWebJobs`, it looks like its performing a lot of work in creating another `IWebJobsBuilder`, causing a lot of side-effects. So far, I have observed difficulties in terminating a function host, multiple host lock leases and so forth.

I think the better approach (at least for Functions V3/V4) would be (note the `IWebJobsStartup`):

```csharp
[assembly: WebJobsStartup(typeof(MyNamespace.WebJobsStartup))]

namespace MyNamespace;

public class WebJobsStartup : IWebJobsStartup
{
    public void Configure(IWebJobsBuilder builder)
    {
        builder.AddExtension<BindingExtensionsProvider>();
    }
}
```

You can even make this part of the extension. The function metadata generator will pick it up, and put it in the generated `extensions.json`.

What's your thought on this?

**Comment by DennesTorres** [comment]
Sorry for taking so long to reply, I was not focused on this project at the time. Analysing your solution, I think it's a very good solution. 

Could you clarify a bit more about making it part of the extension and the metadata generator you mentioned?

**Comment by basilfx** [comment]
> Sorry for taking so long to reply, I was not focused on this project at the time. Analysing your solution, I think it's a very good solution.

No problem.

> Could you clarify a bit more about making it part of the extension and the metadata generator you mentioned?

For an Azure Functions project, you typically add `Microsoft.NET.Sdk.Functions`. This runs the metadata generator if you build a project. The `extensions.json` metadata (typically found in `My.Functions/bin/output`) contains a list of extensions that should be loaded by the function host.

Using the proposed solution ensures that an entry is added to the `extensions.json` metadata, just like other extension do (for example, the [ServiceBus extension](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.WebJobs.Extensions.ServiceBus_5.7.0/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/ServiceBusWebJobsStartup.cs)). That is because of the assembly attribute, even if you created a separate package containing the extension.
